name: Maven Packaging

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  check-format:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Clang-Format
        run: sudo apt-get install -y clang-format
      - name: Check Code Format
        working-directory: .
        run: |
          sh src/test/resources/check-format.sh
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Dependencies
        working-directory: .
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get update
          sudo apt-get install -y maven openjdk-8-jdk-headless --no-install-recommends
      # third parth -> our own package
      - name: Unit Tests
        working-directory: .
        run: |
          mvn --file 3rdparty.xml clean test
          mvn --file 3rdparty.xml install -DskipTests
          mvn clean test
      - name: Build with Maven
        working-directory: .
        run: mvn package -DskipTests
      - name: Generate Gallery
        working-directory: .
        run: |
          sh -c 'set -ex
            jar=$( echo target/drawio2tikz-*.jar )
            javac -classpath $jar Gallery.java
            java -classpath "$jar:." Gallery
          '
      - name: Upload Generated Tikz Files
        uses: actions/upload-artifact@v4
        with:
          name: tikz-files
          path: resources/*.tex
  gallery:
    runs-on: ubuntu-24.04
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Download Generated Tikz Files
        uses: actions/download-artifact@v4
        with:
          name: tikz-files
          path: resources
      # tikz as well.
      - name: Install Texlive
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get update
          sudo apt-get install -y tar xzdec libfontconfig1 perl wget --no-install-recommends
          wget https://mirrors.rit.edu/CTAN/systems/texlive/tlnet/install-tl-unx.tar.gz -O tl.tgz
          tar xzf tl.tgz
          cd install-tl-*
          test -f ../.github/workflows/tl.profile
          ./install-tl --no-interaction --profile=../.github/workflows/tl.profile
          export PATH="$PATH:/tmp/texlive/bin:/tmp/texlive/bin/x86_64-linux"
          tlmgr install pgf caption standalone footmisc preview pdftex xetex libertinus-fonts psnfss url
          tlmgr update --self --all --no-auto-install --repository=https://mirrors.rit.edu/CTAN/systems/texlive/tlnet
      - name: Compile Tikz Files
        working-directory: .
        run: |
          export PATH="$PATH:/tmp/texlive/bin:/tmp/texlive/bin/x86_64-linux"
          xelatex -halt-on-error -output-directory=./resources -interaction=nonstopmode ./resources/gallery.tex
      # save a copy of generated PDF and log files for debugging
      - name: Pack Gallery Artifact
        working-directory: ./resources
        run: |
          tar czvf gallery.tgz gallery.pdf gallery.log
      - name: Upload Gallery Artifact
        uses: actions/upload-artifact@v4
        with:
          name: gallery-ar
          path: resources/gallery.tgz
